service: users
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-south-1
  memorySize: 256

functions:
  signup:
    handler: functions/users.signup
    events:
      - httpApi:
          path: /users/signup
          method: POST
  signin:
    handler: functions/users.signin
    events:
      - httpApi:
          path: /users/signin
          method: POST
  get_one:
    handler: functions/users.getone
    events:
      - httpApi:
          path: /users/getone
          method: get
  get_all:
    handler: functions/users.getall
    events:
      - httpApi:
          path: /users/getall
          method: get
plugins:
  - serverless-offline
  - serverless-plugin-common-excludes
custom:
  serverless-offline:
    httpPort: 3000
    lambdaPort: 7000