service: users
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x

functions:
  signup:
    handler: functions/users.create
    events:
      - httpApi:
          path: /users/signup
          method: POST
  signin:
    handler: functions/auth.signin
    events:
      - httpApi:
          path: /users/signin
          method: POST
  get_one:
    handler: functions/users.getOne
    events:
      - httpApi:
          path: /users/getone
          method: get
plugins:
  - serverless-offline
custom:
  serverless-offline:
    httpPort: 6000
    lambdaPort: 7000