service: users
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x

functions:
  user_create:
    handler: functions/users.create
    events:
      - httpApi:
          path: /users/create
          method: get
plugins:
  - serverless-offline
custom:
  serverless-offline:
    httpPort: 6000
    lambdaPort: 7000